apiVersion: apps/v1
kind: Deployment
metadata:
  name: flmn-toolbox
  namespace: ops
  labels:
    app.kubernetes.io/name: toolbox
    app.kubernetes.io/version: "20250812"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: toolbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: toolbox
        app.kubernetes.io/version: "20250812"
    spec:
      containers:
        - name: toolbox
          image: "flmn/toolbox:20250812"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
