replicaCount: 1

image:
  repository: flmn/toolbox
  pullPolicy: IfNotPresent
  # tag is sourced from Chart.yaml's appVersion by default
  tag: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 256Mi
